Repository lukas-w/font-logos, pull requests merged in 2023-11, with the labels that each got.

#102 CI: Automate release workflow
  .github/workflows/release.yml
  .github/workflows/release_npm.yml
  .github/workflows/update-assets.yml
  README.md
  package.json
  yarn.lock
Labels: enhancement

#106 Add logos from the maker scene.
  README.md
  icons.tsv
  vectors/arduino.svg
  vectors/kicad.svg
  vectors/octoprint.svg
  vectors/openscad.svg
  vectors/osh.svg
  vectors/oshwa.svg
  vectors/prusaslicer.svg
  vectors/reprap.svg
  vectors/riscv.svg
Labels: enhancement, Ready ⛱

#105 Add logos from window managers.
  README.md
  icons.tsv
  vectors/awesome.svg
  vectors/bspwm.svg
  vectors/dwm.svg
  vectors/enlightenment.svg
  vectors/fluxbox.svg
  vectors/hyprland.svg
  vectors/i3.svg
  vectors/jwm.svg
  vectors/qtile.svg
  vectors/sway.svg
  vectors/xmonad.svg
Labels: enhancement, Ready ⛱

#103 Add some logos for GNU/Linux desktop related projects.
  icons.tsv
  vectors/cinnamon.svg
  vectors/freedesktop.svg
  vectors/gnome.svg
  vectors/gtk.svg
  vectors/lxde.svg
  vectors/lxqt.svg
  vectors/mate.svg
  vectors/vanilla.svg
  vectors/wayland.svg
  vectors/xfce.svg
  vectors/xorg.svg
Labels: enhancement, Ready ⛱

#109 Fix: doc: Add releasing instructions
  templates/README.md.njk
Labels: Ready ⛱

#108 Add logos from organizations and services
  vectors/fdroid.svg
  vectors/fosdem.svg
  vectors/osi.svg
  vectors/wikimedia.svg
Labels: enhancement, Ready ⛱
